// <auto-generated />
namespace NewMigrationTracker.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addCommentsAndStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCommentsAndStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201304202125238_addCommentsAndStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
