// <auto-generated />
namespace NewMigrationTracker.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CommentUserID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CommentUserID));
        
        string IMigrationMetadata.Id
        {
            get { return "201304211442522_CommentUserID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
