// <auto-generated />
namespace NewMigrationTracker.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addRelease : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addRelease));
        
        string IMigrationMetadata.Id
        {
            get { return "201304201931059_addRelease"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
