// <auto-generated />
namespace NewMigrationTracker.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class undoteamdata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(undoteamdata));
        
        string IMigrationMetadata.Id
        {
            get { return "201304202021356_undoteamdata"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
